### ISSUE TITLE
[STUDY] 리프레시 토큰 저장 방식 변경

### ISSUE THREAD

**Issue by waveofmymind** [PuddyProject/Puddy_BackEnd#18]
# TODO
- [X] 리프레시 토큰 저장 방식을 RDB -> Redis로 변경 고려
- [x] Redis가 RDB에 비해 가지는 장점 조사
- [x] Redis 학습 및 연습
- [x] 프로젝트 투입

**Comment by waveofmymind** [comment]
1. 성능: Redis는 인메모리 데이터 스토리지로, 데이터베이스에 비해 훨씬 빠른 응답 시간을 제공할 수 있다. 리프레시 토큰을 빠르게 조회하거나 저장할 수 있어 로그인 인증 과정에서의 성능 향상을 이룰 수 있을 것.

2. 유효기간 설정: Redis는 키-값 쌍에 대해 만료 시간을 설정할 수 있어, 리프레시 토큰의 유효기간을 쉽게 관리할 수 있다. 리프레시 토큰이 만료되면 자동으로 삭제되므로, 불필요한 데이터를 관리하지 않아도 될 것

3. 스케일링 및 가용성: Redis는 분산 시스템에서의 스케일링과 가용성을 지원합니다. 클러스터 구성을 통해 리프레시 토큰 데이터를 여러 노드에 분산시키거나, 복제를 통해 데이터의 안정성을 높일 수 있을 것

4. 안전한 데이터 저장: Redis는 디스크에 스냅샷을 생성하여 데이터를 영구적으로 저장할 수 있다. 이를 통해 시스템 장애 시에도 리프레시 토큰 데이터를 복구할 수 있을 것
